config/routes.rb
MDNS::Application.routes.draw do

  scope "/knox" do
    resource :gate, :controller => 'user_sessions', :path_names => { :new => 'open' } do
      get 'logout', :action => 'destroy'
    end
    resource :account, :controller => 'users', :path_names => { :new => 'register' }, :except => :destroy
  end
  
  scope "/rw" do
    resources :domains, :except => [:new, :edit] do
      resources :records, :except => [:new, :edit]
      member do
        post 'publish'
      end
    end
    resources :recordtypes, :only => :index
  end
  
  scope '/admin' do
    get '/', :to => "admin#index" 
    resources :users, :controller => 'admin_users', :except => :new
    resources :domains, :controller => 'admin_domains', :as => 'admin_domain', :except => :new do
      put :toggle
    end
  end

  root :to => "home#index"
end

app/controllers/admin_domains_controller.rb
class AdminDomainsController < ApplicationController
  
  before_filter :require_user
  before_filter :require_admin
  
  def index
    @domains = Domain.order('fqdn ASC').all
  end
  
  def toggle
    @domain = Domain.find(params[:admin_domain_id])
    @domain.active = !@domain.active
    @domain.save
    redirect_to admin_domain_index_path
  end
  
end

app/views/admin_domains/index.html.erb
<h2>Admin Tools:</h2>

<table style="width: 100%">
	<tr>
		<th>Domain</th>
		<th>Active</th>
		<th>User</th>
		<th>&nbsp;</th>
	</tr>
	<% @domains.each do |domain| -%>
		<tr>
			<td colspan=""><%= domain.fqdn %></td>
			<td colspan=""><%= link_to domain.active? ? "Yes": "No", admin_domain_toggle_path(domain), :method => :put %></td>
			<td colspan=""><%= domain.user.email %></td>
			<td colspan=""><%= link_to "Delete", admin_domain_path(domain), :method => :delete %></td>
		</tr>
	<% end -%>
</table>