config/routes.rb
MDNS::Application.routes.draw do

  scope "/knox" do
    resource :gate, :controller => 'user_sessions', :path_names => { :new => 'open' } do
      get 'logout', :action => 'destroy'
    end
    resource :account, :controller => 'users', :path_names => { :new => 'register' }, :except => :destroy
  end
  
  scope "/rw" do
    resources :domains, :except => [:new, :edit] do
      resources :records, :except => [:new, :edit]
      member do
        post 'publish'
      end
    end
    resources :recordtypes, :only => :index
  end
  
  scope '/admin' do
    get '/', :to => "admin#index" 
    resources :users, :controller => 'admin_users', :except => :new
    resources :domains, :controller => 'admin_domains', :as => 'admin_domain', :except => :new do
      put :toggle
    end
  end

  root :to => "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>M DNS</title>	
  <%= stylesheet_link_tag :all %>

	<link rel="stylesheet" href="/mdns/domain.css" type="text/css" media="screen" title="no title" charset="utf-8">
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body class="softwareupdate">
	<div id="signinBox">
		<div id="appVersion">v2.0</div>
		<% if current_user -%>
			Hi, <%= current_user.first_name %> |
			<%= link_to "Edit account", account_path %> |
			<%= link_to "Log out", gate_path, :method => :delete %> |
		<% else -%>
			<%= link_to "Log in", new_gate_path %> |
		<% end -%>
		<a href="http://ae.m.ac.nz/" id="page-badge-global"><span>ae.m.ac.nz</span></a> |
		<a href="http://m.ac.nz/" id="page-badge-local"><span>m.ac.nz</span></a>
	</div>

  <div id="header">	
    <h1><%= @subtitle || "M DNS" %></h1>
  </div>
  <div id="page">
	<%= yield %>
  </div>

  <div id="footer">
    <p>
      &copy; 2010 Patrick Quinn-Graham with <a href="http://soapbox.co.nz/rights-reserved">some rights reserved</a>. 
    </p>
  </div>

<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
<script type="text/javascript">
_uacct = "UA-340421-5";
urchinTracker();
</script>
</body>
</html>